# Generated by Django 6.0.6 on 2026-08-03 14:23

import django.db.models.deletion
import services.idgenerator_svc
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0002_store_slog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_customer', models.CharField(max_length=100, verbose_name='Nome do cliente')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('observation', models.TextField(blank=True, max_length=250, null=True, verbose_name='Observação')),
                ('address', models.TextField(max_length=200, verbose_name='Endereço')),
                ('house_number', models.CharField(blank=True, null=True, verbose_name='Número da casa')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True, verbose_name='Longitude')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Subtotal')),
                ('remaining', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Troco')),
                ('payment_method', models.CharField(blank=True, max_length=15, null=True, verbose_name='Pago com')),
                ('rate_delivery', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Taxa de Entrega')),
                ('code', models.CharField(default=services.idgenerator_svc.generate_Code, max_length=5, verbose_name='Código Entrega')),
                ('status', models.CharField(choices=[('pending', 'pendente'), ('delivered', 'entregue'), ('canceled', 'cancelado')], default='pending', max_length=10, verbose_name='Status')),
                ('itens', models.JSONField(verbose_name='Lista de Itens')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stores.store', verbose_name='Loja')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-created_at'],
            },
        ),
    ]
