# Generated by Django 6.0.6 on 2026-08-08 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('stores', '0002_store_slog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Subtotal')),
                ('remaining', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Troco')),
                ('payment_method', models.CharField(blank=True, max_length=15, null=True, verbose_name='Pago com')),
                ('rate_delivery', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Taxa de Entrega')),
                ('collaborator', models.CharField(blank=True, max_length=50, null=True, verbose_name='Colaborador')),
                ('observation', models.TextField(blank=True, max_length=200, null=True, verbose_name='Observação')),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to=settings.AUTH_USER_MODEL, verbose_name='Conta')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='orders.order', verbose_name='Pedido')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stores', to='stores.store', verbose_name='Loja')),
            ],
            options={
                'verbose_name': 'Venda',
                'verbose_name_plural': 'Vendas',
                'ordering': ['-created_at'],
            },
        ),
    ]
