# Generated by Django 6.0.6 on 2026-07-31 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='slog',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Slogan'),
        ),
    ]
